services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./database/:/app/database/
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=hf.co/LatitudeGames/Wayfarer-12B-GGUF:IQ4_XS
      - LOG_LEVEL=DEBUG
      - DATABASE_FILE=database/database.db
      - CORS_ORIGINS=https://localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    volumes:
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
